name: dart_express
description: An unopinionated express-like HTTP framework built in Dart, includes the ability to render Mustache, Jael and HTML files, and simple routing.
version: 0.5.3
homepage: https://github.com/deriegle/dart-express

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  path: ^1.6.4
  file: ^5.0.0
  http: ^0.12.0+2
  meta: ^1.1.7
  path_to_regexp: ^0.2.1
  markdown: ^2.1.3
  code_buffer: ^1.0.1
  symbol_table: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
  test: ^1.6.0
